/*
 * Toolshop API
 * Toolshop REST API technical description
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@testsmith.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.practicesoftwaretesting.client.api;

import com.practicesoftwaretesting.client.ApiCallback;
import com.practicesoftwaretesting.client.ApiClient;
import com.practicesoftwaretesting.client.ApiException;
import com.practicesoftwaretesting.client.ApiResponse;
import com.practicesoftwaretesting.client.Configuration;
import com.practicesoftwaretesting.client.Pair;
import com.practicesoftwaretesting.client.ProgressRequestBody;
import com.practicesoftwaretesting.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.practicesoftwaretesting.client.model.BrandRequest;
import com.practicesoftwaretesting.client.model.BrandResponse;
import com.practicesoftwaretesting.client.model.ItemNotFoundResponse;
import com.practicesoftwaretesting.client.model.MethodNotAllowedResponse;
import com.practicesoftwaretesting.client.model.ResourceNotFoundResponse;
import com.practicesoftwaretesting.client.model.UpdateResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BrandApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public BrandApi() {
        this(Configuration.getDefaultApiClient());
    }

    public BrandApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deleteBrand
     * @param brandId The brandId parameter in path (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Returns when the entity is used elsewhere </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteBrandCall(Integer brandId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/brands/{brandId}"
            .replace("{" + "brandId" + "}", localVarApiClient.escapeString(brandId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteBrandValidateBeforeCall(Integer brandId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'brandId' is set
        if (brandId == null) {
            throw new ApiException("Missing the required parameter 'brandId' when calling deleteBrand(Async)");
        }

        return deleteBrandCall(brandId, _callback);

    }

    /**
     * Delete specific brand
     * 
     * @param brandId The brandId parameter in path (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Returns when the entity is used elsewhere </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public void deleteBrand(Integer brandId) throws ApiException {
        deleteBrandWithHttpInfo(brandId);
    }

    /**
     * Delete specific brand
     * 
     * @param brandId The brandId parameter in path (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Returns when the entity is used elsewhere </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteBrandWithHttpInfo(Integer brandId) throws ApiException {
        okhttp3.Call localVarCall = deleteBrandValidateBeforeCall(brandId, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete specific brand (asynchronously)
     * 
     * @param brandId The brandId parameter in path (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Returns when the entity is used elsewhere </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteBrandAsync(Integer brandId, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteBrandValidateBeforeCall(brandId, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for getBrand
     * @param brandId The brandId parameter in path (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getBrandCall(Integer brandId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/brands/{brandId}"
            .replace("{" + "brandId" + "}", localVarApiClient.escapeString(brandId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getBrandValidateBeforeCall(Integer brandId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'brandId' is set
        if (brandId == null) {
            throw new ApiException("Missing the required parameter 'brandId' when calling getBrand(Async)");
        }

        return getBrandCall(brandId, _callback);

    }

    /**
     * Retrieve specific brand
     * Retrieve specific brand
     * @param brandId The brandId parameter in path (required)
     * @return BrandResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public BrandResponse getBrand(Integer brandId) throws ApiException {
        ApiResponse<BrandResponse> localVarResp = getBrandWithHttpInfo(brandId);
        return localVarResp.getData();
    }

    /**
     * Retrieve specific brand
     * Retrieve specific brand
     * @param brandId The brandId parameter in path (required)
     * @return ApiResponse&lt;BrandResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BrandResponse> getBrandWithHttpInfo(Integer brandId) throws ApiException {
        okhttp3.Call localVarCall = getBrandValidateBeforeCall(brandId, null);
        Type localVarReturnType = new TypeToken<BrandResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve specific brand (asynchronously)
     * Retrieve specific brand
     * @param brandId The brandId parameter in path (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getBrandAsync(Integer brandId, final ApiCallback<BrandResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getBrandValidateBeforeCall(brandId, _callback);
        Type localVarReturnType = new TypeToken<BrandResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getBrands
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getBrandsCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/brands";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getBrandsValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getBrandsCall(_callback);

    }

    /**
     * Retrieve all brands
     * Retrieve all brands
     * @return List&lt;BrandResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public List<BrandResponse> getBrands() throws ApiException {
        ApiResponse<List<BrandResponse>> localVarResp = getBrandsWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Retrieve all brands
     * Retrieve all brands
     * @return ApiResponse&lt;List&lt;BrandResponse&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<BrandResponse>> getBrandsWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getBrandsValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<BrandResponse>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve all brands (asynchronously)
     * Retrieve all brands
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getBrandsAsync(final ApiCallback<List<BrandResponse>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getBrandsValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<BrandResponse>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for storeBrand
     * @param brandRequest Brand request object (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call storeBrandCall(BrandRequest brandRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = brandRequest;

        // create path and map variables
        String localVarPath = "/brands";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call storeBrandValidateBeforeCall(BrandRequest brandRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'brandRequest' is set
        if (brandRequest == null) {
            throw new ApiException("Missing the required parameter 'brandRequest' when calling storeBrand(Async)");
        }

        return storeBrandCall(brandRequest, _callback);

    }

    /**
     * Store new brand
     * Store new brand
     * @param brandRequest Brand request object (required)
     * @return BrandResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public BrandResponse storeBrand(BrandRequest brandRequest) throws ApiException {
        ApiResponse<BrandResponse> localVarResp = storeBrandWithHttpInfo(brandRequest);
        return localVarResp.getData();
    }

    /**
     * Store new brand
     * Store new brand
     * @param brandRequest Brand request object (required)
     * @return ApiResponse&lt;BrandResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BrandResponse> storeBrandWithHttpInfo(BrandRequest brandRequest) throws ApiException {
        okhttp3.Call localVarCall = storeBrandValidateBeforeCall(brandRequest, null);
        Type localVarReturnType = new TypeToken<BrandResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Store new brand (asynchronously)
     * Store new brand
     * @param brandRequest Brand request object (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call storeBrandAsync(BrandRequest brandRequest, final ApiCallback<BrandResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = storeBrandValidateBeforeCall(brandRequest, _callback);
        Type localVarReturnType = new TypeToken<BrandResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateBrand
     * @param brandId The brandId parameter in path (required)
     * @param brandRequest Brand request object (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Result of the update </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateBrandCall(Integer brandId, BrandRequest brandRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = brandRequest;

        // create path and map variables
        String localVarPath = "/brands/{brandId}"
            .replace("{" + "brandId" + "}", localVarApiClient.escapeString(brandId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateBrandValidateBeforeCall(Integer brandId, BrandRequest brandRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'brandId' is set
        if (brandId == null) {
            throw new ApiException("Missing the required parameter 'brandId' when calling updateBrand(Async)");
        }

        // verify the required parameter 'brandRequest' is set
        if (brandRequest == null) {
            throw new ApiException("Missing the required parameter 'brandRequest' when calling updateBrand(Async)");
        }

        return updateBrandCall(brandId, brandRequest, _callback);

    }

    /**
     * Update specific brand
     * Update specific brand
     * @param brandId The brandId parameter in path (required)
     * @param brandRequest Brand request object (required)
     * @return UpdateResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Result of the update </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public UpdateResponse updateBrand(Integer brandId, BrandRequest brandRequest) throws ApiException {
        ApiResponse<UpdateResponse> localVarResp = updateBrandWithHttpInfo(brandId, brandRequest);
        return localVarResp.getData();
    }

    /**
     * Update specific brand
     * Update specific brand
     * @param brandId The brandId parameter in path (required)
     * @param brandRequest Brand request object (required)
     * @return ApiResponse&lt;UpdateResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Result of the update </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<UpdateResponse> updateBrandWithHttpInfo(Integer brandId, BrandRequest brandRequest) throws ApiException {
        okhttp3.Call localVarCall = updateBrandValidateBeforeCall(brandId, brandRequest, null);
        Type localVarReturnType = new TypeToken<UpdateResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update specific brand (asynchronously)
     * Update specific brand
     * @param brandId The brandId parameter in path (required)
     * @param brandRequest Brand request object (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Result of the update </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateBrandAsync(Integer brandId, BrandRequest brandRequest, final ApiCallback<UpdateResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateBrandValidateBeforeCall(brandId, brandRequest, _callback);
        Type localVarReturnType = new TypeToken<UpdateResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
