/*
 * Toolshop API
 * Toolshop REST API technical description
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@testsmith.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.practicesoftwaretesting.client.api;

import com.practicesoftwaretesting.client.ApiCallback;
import com.practicesoftwaretesting.client.ApiClient;
import com.practicesoftwaretesting.client.ApiException;
import com.practicesoftwaretesting.client.ApiResponse;
import com.practicesoftwaretesting.client.Configuration;
import com.practicesoftwaretesting.client.Pair;
import com.practicesoftwaretesting.client.ProgressRequestBody;
import com.practicesoftwaretesting.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.practicesoftwaretesting.client.model.ItemNotFoundResponse;
import com.practicesoftwaretesting.client.model.MethodNotAllowedResponse;
import com.practicesoftwaretesting.client.model.ProductRequest;
import com.practicesoftwaretesting.client.model.ProductResponse;
import com.practicesoftwaretesting.client.model.StoreProductResponse;
import com.practicesoftwaretesting.client.model.UpdateResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProductApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ProductApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ProductApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deleteProduct
     * @param productId The productId parameter in path (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Returns when the entity is used elsewhere </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteProductCall(Integer productId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/products/{productId}"
            .replace("{" + "productId" + "}", localVarApiClient.escapeString(productId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteProductValidateBeforeCall(Integer productId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'productId' is set
        if (productId == null) {
            throw new ApiException("Missing the required parameter 'productId' when calling deleteProduct(Async)");
        }

        return deleteProductCall(productId, _callback);

    }

    /**
     * Delete specific product
     * 
     * @param productId The productId parameter in path (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Returns when the entity is used elsewhere </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public void deleteProduct(Integer productId) throws ApiException {
        deleteProductWithHttpInfo(productId);
    }

    /**
     * Delete specific product
     * 
     * @param productId The productId parameter in path (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Returns when the entity is used elsewhere </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteProductWithHttpInfo(Integer productId) throws ApiException {
        okhttp3.Call localVarCall = deleteProductValidateBeforeCall(productId, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete specific product (asynchronously)
     * 
     * @param productId The productId parameter in path (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Returns when the entity is used elsewhere </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteProductAsync(Integer productId, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteProductValidateBeforeCall(productId, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for getProduct
     * @param productId The productId parameter in path (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductCall(Integer productId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/products/{productId}"
            .replace("{" + "productId" + "}", localVarApiClient.escapeString(productId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getProductValidateBeforeCall(Integer productId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'productId' is set
        if (productId == null) {
            throw new ApiException("Missing the required parameter 'productId' when calling getProduct(Async)");
        }

        return getProductCall(productId, _callback);

    }

    /**
     * Retrieve specific product
     * Retrieve specific product
     * @param productId The productId parameter in path (required)
     * @return ProductResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public ProductResponse getProduct(Integer productId) throws ApiException {
        ApiResponse<ProductResponse> localVarResp = getProductWithHttpInfo(productId);
        return localVarResp.getData();
    }

    /**
     * Retrieve specific product
     * Retrieve specific product
     * @param productId The productId parameter in path (required)
     * @return ApiResponse&lt;ProductResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ProductResponse> getProductWithHttpInfo(Integer productId) throws ApiException {
        okhttp3.Call localVarCall = getProductValidateBeforeCall(productId, null);
        Type localVarReturnType = new TypeToken<ProductResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve specific product (asynchronously)
     * Retrieve specific product
     * @param productId The productId parameter in path (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductAsync(Integer productId, final ApiCallback<ProductResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getProductValidateBeforeCall(productId, _callback);
        Type localVarReturnType = new TypeToken<ProductResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getProducts
     * @param byBrand Id of brand (optional)
     * @param byCategory Id of category (optional)
     * @param isRental Indication if we like to retrieve rentals products (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductsCall(Integer byBrand, Integer byCategory, String isRental, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/products";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (byBrand != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("by_brand", byBrand));
        }

        if (byCategory != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("by_category", byCategory));
        }

        if (isRental != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("is_rental", isRental));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getProductsValidateBeforeCall(Integer byBrand, Integer byCategory, String isRental, final ApiCallback _callback) throws ApiException {
        return getProductsCall(byBrand, byCategory, isRental, _callback);

    }

    /**
     * Retrieve all products
     * Retrieve all products
     * @param byBrand Id of brand (optional)
     * @param byCategory Id of category (optional)
     * @param isRental Indication if we like to retrieve rentals products (optional)
     * @return List&lt;ProductResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public List<ProductResponse> getProducts(Integer byBrand, Integer byCategory, String isRental) throws ApiException {
        ApiResponse<List<ProductResponse>> localVarResp = getProductsWithHttpInfo(byBrand, byCategory, isRental);
        return localVarResp.getData();
    }

    /**
     * Retrieve all products
     * Retrieve all products
     * @param byBrand Id of brand (optional)
     * @param byCategory Id of category (optional)
     * @param isRental Indication if we like to retrieve rentals products (optional)
     * @return ApiResponse&lt;List&lt;ProductResponse&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<ProductResponse>> getProductsWithHttpInfo(Integer byBrand, Integer byCategory, String isRental) throws ApiException {
        okhttp3.Call localVarCall = getProductsValidateBeforeCall(byBrand, byCategory, isRental, null);
        Type localVarReturnType = new TypeToken<List<ProductResponse>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve all products (asynchronously)
     * Retrieve all products
     * @param byBrand Id of brand (optional)
     * @param byCategory Id of category (optional)
     * @param isRental Indication if we like to retrieve rentals products (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductsAsync(Integer byBrand, Integer byCategory, String isRental, final ApiCallback<List<ProductResponse>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getProductsValidateBeforeCall(byBrand, byCategory, isRental, _callback);
        Type localVarReturnType = new TypeToken<List<ProductResponse>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getRelatedProducts
     * @param productId The productId parameter in path (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRelatedProductsCall(Integer productId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/products/{productId}/related"
            .replace("{" + "productId" + "}", localVarApiClient.escapeString(productId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getRelatedProductsValidateBeforeCall(Integer productId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'productId' is set
        if (productId == null) {
            throw new ApiException("Missing the required parameter 'productId' when calling getRelatedProducts(Async)");
        }

        return getRelatedProductsCall(productId, _callback);

    }

    /**
     * Retrieve related products
     * Retrieve related products
     * @param productId The productId parameter in path (required)
     * @return List&lt;ProductResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public List<ProductResponse> getRelatedProducts(Integer productId) throws ApiException {
        ApiResponse<List<ProductResponse>> localVarResp = getRelatedProductsWithHttpInfo(productId);
        return localVarResp.getData();
    }

    /**
     * Retrieve related products
     * Retrieve related products
     * @param productId The productId parameter in path (required)
     * @return ApiResponse&lt;List&lt;ProductResponse&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<ProductResponse>> getRelatedProductsWithHttpInfo(Integer productId) throws ApiException {
        okhttp3.Call localVarCall = getRelatedProductsValidateBeforeCall(productId, null);
        Type localVarReturnType = new TypeToken<List<ProductResponse>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve related products (asynchronously)
     * Retrieve related products
     * @param productId The productId parameter in path (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRelatedProductsAsync(Integer productId, final ApiCallback<List<ProductResponse>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getRelatedProductsValidateBeforeCall(productId, _callback);
        Type localVarReturnType = new TypeToken<List<ProductResponse>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for storeProduct
     * @param productRequest Product request object (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Returns when product is created </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call storeProductCall(ProductRequest productRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = productRequest;

        // create path and map variables
        String localVarPath = "/products";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call storeProductValidateBeforeCall(ProductRequest productRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'productRequest' is set
        if (productRequest == null) {
            throw new ApiException("Missing the required parameter 'productRequest' when calling storeProduct(Async)");
        }

        return storeProductCall(productRequest, _callback);

    }

    /**
     * Store new product
     * Store new product
     * @param productRequest Product request object (required)
     * @return StoreProductResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Returns when product is created </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public StoreProductResponse storeProduct(ProductRequest productRequest) throws ApiException {
        ApiResponse<StoreProductResponse> localVarResp = storeProductWithHttpInfo(productRequest);
        return localVarResp.getData();
    }

    /**
     * Store new product
     * Store new product
     * @param productRequest Product request object (required)
     * @return ApiResponse&lt;StoreProductResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Returns when product is created </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<StoreProductResponse> storeProductWithHttpInfo(ProductRequest productRequest) throws ApiException {
        okhttp3.Call localVarCall = storeProductValidateBeforeCall(productRequest, null);
        Type localVarReturnType = new TypeToken<StoreProductResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Store new product (asynchronously)
     * Store new product
     * @param productRequest Product request object (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Returns when product is created </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call storeProductAsync(ProductRequest productRequest, final ApiCallback<StoreProductResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = storeProductValidateBeforeCall(productRequest, _callback);
        Type localVarReturnType = new TypeToken<StoreProductResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateProduct
     * @param productId The productId parameter in path (required)
     * @param productRequest Product request object (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Result of the update </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateProductCall(Integer productId, ProductRequest productRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = productRequest;

        // create path and map variables
        String localVarPath = "/products/{productId}"
            .replace("{" + "productId" + "}", localVarApiClient.escapeString(productId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateProductValidateBeforeCall(Integer productId, ProductRequest productRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'productId' is set
        if (productId == null) {
            throw new ApiException("Missing the required parameter 'productId' when calling updateProduct(Async)");
        }

        // verify the required parameter 'productRequest' is set
        if (productRequest == null) {
            throw new ApiException("Missing the required parameter 'productRequest' when calling updateProduct(Async)");
        }

        return updateProductCall(productId, productRequest, _callback);

    }

    /**
     * Update specific product
     * Update specific product
     * @param productId The productId parameter in path (required)
     * @param productRequest Product request object (required)
     * @return UpdateResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Result of the update </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public UpdateResponse updateProduct(Integer productId, ProductRequest productRequest) throws ApiException {
        ApiResponse<UpdateResponse> localVarResp = updateProductWithHttpInfo(productId, productRequest);
        return localVarResp.getData();
    }

    /**
     * Update specific product
     * Update specific product
     * @param productId The productId parameter in path (required)
     * @param productRequest Product request object (required)
     * @return ApiResponse&lt;UpdateResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Result of the update </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<UpdateResponse> updateProductWithHttpInfo(Integer productId, ProductRequest productRequest) throws ApiException {
        okhttp3.Call localVarCall = updateProductValidateBeforeCall(productId, productRequest, null);
        Type localVarReturnType = new TypeToken<UpdateResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update specific product (asynchronously)
     * Update specific product
     * @param productId The productId parameter in path (required)
     * @param productRequest Product request object (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Result of the update </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Returns when the resource is not found </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Returns when the method is not allowed for the requested route </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Returns when the server was not able to process the content </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateProductAsync(Integer productId, ProductRequest productRequest, final ApiCallback<UpdateResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateProductValidateBeforeCall(productId, productRequest, _callback);
        Type localVarReturnType = new TypeToken<UpdateResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
