/*
 * Toolshop API
 * Toolshop REST API technical description
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@testsmith.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.practicesoftwaretesting.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BrandRequest
 */
public class BrandRequestTest {
    private final BrandRequest model = new BrandRequest();

    /**
     * Model tests for BrandRequest
     */
    @Test
    public void testBrandRequest() {
        // TODO: test BrandRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

}
