/*
 * Toolshop API
 * Toolshop REST API technical description
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@testsmith.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.practicesoftwaretesting.client.api;

import com.practicesoftwaretesting.client.ApiException;
import com.practicesoftwaretesting.client.model.CategoryRequest;
import com.practicesoftwaretesting.client.model.CategoryResponse;
import com.practicesoftwaretesting.client.model.CategoryTreeResponse;
import com.practicesoftwaretesting.client.model.ItemNotFoundResponse;
import com.practicesoftwaretesting.client.model.MethodNotAllowedResponse;
import com.practicesoftwaretesting.client.model.ResourceNotFoundResponse;
import com.practicesoftwaretesting.client.model.UpdateResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CategoryApi
 */
@Disabled
public class CategoryApiTest {

    private final CategoryApi api = new CategoryApi();

    /**
     * Delete specific category
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteCategoryTest() throws ApiException {
        Integer categoryId = null;
        api.deleteCategory(categoryId);
        // TODO: test validations
    }

    /**
     * Retrieve all categories
     *
     * Retrieve all categories
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCategoriesTest() throws ApiException {
        List<CategoryResponse> response = api.getCategories();
        // TODO: test validations
    }

    /**
     * Retrieve all categories (including subcategories)
     *
     * Retrieve all categories (including subcategories)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCategoriesTreeTest() throws ApiException {
        String byCategorySlug = null;
        List<CategoryTreeResponse> response = api.getCategoriesTree(byCategorySlug);
        // TODO: test validations
    }

    /**
     * Retrieve specific category (including subcategories)
     *
     * Retrieve specific category (including subcategories)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCategoryTest() throws ApiException {
        Integer categoryId = null;
        CategoryTreeResponse response = api.getCategory(categoryId);
        // TODO: test validations
    }

    /**
     * Store new category
     *
     * Store new category
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void storeCategoryTest() throws ApiException {
        CategoryRequest categoryRequest = null;
        CategoryResponse response = api.storeCategory(categoryRequest);
        // TODO: test validations
    }

    /**
     * Update specific category
     *
     * Update specific category
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateCategoryTest() throws ApiException {
        Integer categoryId = null;
        CategoryRequest categoryRequest = null;
        UpdateResponse response = api.updateCategory(categoryId, categoryRequest);
        // TODO: test validations
    }

}
