/*
 * Toolshop API
 * Toolshop REST API technical description
 *
 * OpenAPI spec version: 0.4.0
 * Contact: info@testsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.practicesoftwaretesting.client.api;

import com.practicesoftwaretesting.client.model.FavoriteRequest;
import com.practicesoftwaretesting.client.model.FavoriteResponse;
import com.practicesoftwaretesting.client.model.InlineResponse200;
import com.practicesoftwaretesting.client.model.InlineResponse401;
import com.practicesoftwaretesting.client.model.InlineResponse404;
import com.practicesoftwaretesting.client.model.InlineResponse4041;
import com.practicesoftwaretesting.client.model.InlineResponse405;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for FavoriteApi
 */
@Ignore
public class FavoriteApiTest {

    private final FavoriteApi api = new FavoriteApi();

    /**
     * Delete specific favorite
     *
     * User role is required to delete a specific favorite
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteFavoriteTest() throws Exception {
        Integer favoriteId = null;
        api.deleteFavorite(favoriteId);

        // TODO: test validations
    }
    /**
     * Retrieve specific favorite
     *
     * User role is required to retrieve specific favorite
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getFavoriteTest() throws Exception {
        Integer favoriteId = null;
        FavoriteResponse response = api.getFavorite(favoriteId);

        // TODO: test validations
    }
    /**
     * Retrieve all favorites
     *
     * User role is required to retrieve users favorites
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getFavoritesTest() throws Exception {
        List<FavoriteResponse> response = api.getFavorites();

        // TODO: test validations
    }
    /**
     * Store new favorite
     *
     * User role is required to store new favorite
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void storeFavoriteTest() throws Exception {
        FavoriteRequest body = null;
        FavoriteResponse response = api.storeFavorite(body);

        // TODO: test validations
    }
    /**
     * Update specific favorite
     *
     * User role is required to update specific favorite
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateFavoriteTest() throws Exception {
        FavoriteRequest body = null;
        Integer favoriteId = null;
        InlineResponse200 response = api.updateFavorite(body, favoriteId);

        // TODO: test validations
    }
}
