/*
 * Toolshop API
 * Toolshop REST API technical description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@testsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.practicesoftwaretesting.client.api;

import com.practicesoftwaretesting.client.model.InlineResponse401;
import com.practicesoftwaretesting.client.model.InlineResponse404;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ReportApi
 */
@Ignore
public class ReportApiTest {

    private final ReportApi api = new ReportApi();

    /**
     * Get average sales per month
     *
     * &#x60;Admin&#x60; role is required to get average sales per month
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAverageSalesPerMonthTest() throws Exception {
        Integer year = null;
        List<Object> response = api.getAverageSalesPerMonth(year);

        // TODO: test validations
    }
    /**
     * Get average sales per week
     *
     * &#x60;Admin&#x60; role is required to get average sales per week
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAverageSalesPerWeekTest() throws Exception {
        Integer year = null;
        List<Object> response = api.getAverageSalesPerWeek(year);

        // TODO: test validations
    }
    /**
     * Get top 10 best selling categories
     *
     * &#x60;Admin&#x60; role is required to get top 10 best selling categories
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getBestSellingCategoriesTest() throws Exception {
        List<Object> response = api.getBestSellingCategories();

        // TODO: test validations
    }
    /**
     * Get customers by country
     *
     * &#x60;Admin&#x60; role is required to get customers by country
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCustomersByCountryTest() throws Exception {
        String country = null;
        List<Object> response = api.getCustomersByCountry(country);

        // TODO: test validations
    }
    /**
     * Get top 10 purchased products
     *
     * &#x60;Admin&#x60; role is required to get top 10 purchased products
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTopPurchasedProductsTest() throws Exception {
        List<Object> response = api.getTopPurchasedProducts();

        // TODO: test validations
    }
    /**
     * Get total sales of years
     *
     * &#x60;Admin&#x60; role is required to get total sales of years
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTotalSalesOfYearsTest() throws Exception {
        Integer years = null;
        List<Object> response = api.getTotalSalesOfYears(years);

        // TODO: test validations
    }
    /**
     * Get total sales per country
     *
     * &#x60;Admin&#x60; role is required to get total sales per country
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTotalSalesPerCountryTest() throws Exception {
        List<Object> response = api.getTotalSalesPerCountry();

        // TODO: test validations
    }
}
