/*
 * Toolshop API
 * Toolshop REST API technical description
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@testsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.practicesoftwaretesting.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * GiftCardDetails
 */

@javax.annotation.Generated(value = "com.tesuqa.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-20T15:32:30.637801580Z[GMT]")

public class GiftCardDetails implements OneOfBaseInvoiceRequestPaymentDetails, OneOfpaymentCheckBodyPaymentDetails {
  @SerializedName("gift_card_number")
  private String giftCardNumber = null;

  @SerializedName("validation_code")
  private String validationCode = null;

  public GiftCardDetails giftCardNumber(String giftCardNumber) {
    this.giftCardNumber = giftCardNumber;
    return this;
  }

   /**
   * Get giftCardNumber
   * @return giftCardNumber
  **/
  @Schema(description = "")
  public String getGiftCardNumber() {
    return giftCardNumber;
  }

  public void setGiftCardNumber(String giftCardNumber) {
    this.giftCardNumber = giftCardNumber;
  }

  public GiftCardDetails validationCode(String validationCode) {
    this.validationCode = validationCode;
    return this;
  }

   /**
   * Get validationCode
   * @return validationCode
  **/
  @Schema(description = "")
  public String getValidationCode() {
    return validationCode;
  }

  public void setValidationCode(String validationCode) {
    this.validationCode = validationCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GiftCardDetails giftCardDetails = (GiftCardDetails) o;
    return Objects.equals(this.giftCardNumber, giftCardDetails.giftCardNumber) &&
        Objects.equals(this.validationCode, giftCardDetails.validationCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(giftCardNumber, validationCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GiftCardDetails {\n");
    
    sb.append("    giftCardNumber: ").append(toIndentedString(giftCardNumber)).append("\n");
    sb.append("    validationCode: ").append(toIndentedString(validationCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
