/*
 * Toolshop API
 * Toolshop REST API technical description
 *
 * OpenAPI spec version: 4.0.0
 * Contact: info@testsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.practicesoftwaretesting.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.practicesoftwaretesting.client.model.InvoiceResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2002
 */

@javax.annotation.Generated(value = "com.tesuqa.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-22T07:51:27.258669159Z[GMT]")

public class InlineResponse2002 {
  @SerializedName("current_page")
  private Integer currentPage = null;

  @SerializedName("data")
  private List<InvoiceResponse> data = null;

  @SerializedName("from")
  private Integer from = null;

  @SerializedName("last_page")
  private Integer lastPage = null;

  @SerializedName("per_page")
  private Integer perPage = null;

  @SerializedName("to")
  private Integer to = null;

  @SerializedName("total")
  private Integer total = null;

  public InlineResponse2002 currentPage(Integer currentPage) {
    this.currentPage = currentPage;
    return this;
  }

   /**
   * Get currentPage
   * @return currentPage
  **/
  @Schema(example = "1", description = "")
  public Integer getCurrentPage() {
    return currentPage;
  }

  public void setCurrentPage(Integer currentPage) {
    this.currentPage = currentPage;
  }

  public InlineResponse2002 data(List<InvoiceResponse> data) {
    this.data = data;
    return this;
  }

  public InlineResponse2002 addDataItem(InvoiceResponse dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<InvoiceResponse>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public List<InvoiceResponse> getData() {
    return data;
  }

  public void setData(List<InvoiceResponse> data) {
    this.data = data;
  }

  public InlineResponse2002 from(Integer from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @Schema(example = "1", description = "")
  public Integer getFrom() {
    return from;
  }

  public void setFrom(Integer from) {
    this.from = from;
  }

  public InlineResponse2002 lastPage(Integer lastPage) {
    this.lastPage = lastPage;
    return this;
  }

   /**
   * Get lastPage
   * @return lastPage
  **/
  @Schema(example = "1", description = "")
  public Integer getLastPage() {
    return lastPage;
  }

  public void setLastPage(Integer lastPage) {
    this.lastPage = lastPage;
  }

  public InlineResponse2002 perPage(Integer perPage) {
    this.perPage = perPage;
    return this;
  }

   /**
   * Get perPage
   * @return perPage
  **/
  @Schema(example = "1", description = "")
  public Integer getPerPage() {
    return perPage;
  }

  public void setPerPage(Integer perPage) {
    this.perPage = perPage;
  }

  public InlineResponse2002 to(Integer to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @Schema(example = "1", description = "")
  public Integer getTo() {
    return to;
  }

  public void setTo(Integer to) {
    this.to = to;
  }

  public InlineResponse2002 total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @Schema(example = "1", description = "")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return Objects.equals(this.currentPage, inlineResponse2002.currentPage) &&
        Objects.equals(this.data, inlineResponse2002.data) &&
        Objects.equals(this.from, inlineResponse2002.from) &&
        Objects.equals(this.lastPage, inlineResponse2002.lastPage) &&
        Objects.equals(this.perPage, inlineResponse2002.perPage) &&
        Objects.equals(this.to, inlineResponse2002.to) &&
        Objects.equals(this.total, inlineResponse2002.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentPage, data, from, lastPage, perPage, to, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    
    sb.append("    currentPage: ").append(toIndentedString(currentPage)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    lastPage: ").append(toIndentedString(lastPage)).append("\n");
    sb.append("    perPage: ").append(toIndentedString(perPage)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
