/*
 * Toolshop API
 * Toolshop REST API technical description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@testsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.practicesoftwaretesting.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * InlineResponse201
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-01-29T12:39:58.899Z[GMT]")
public class InlineResponse201 {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("price")
  private BigDecimal price = null;

  @SerializedName("is_location_offer")
  private Boolean isLocationOffer = null;

  @SerializedName("is_rental")
  private Boolean isRental = null;

  public InlineResponse201 id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "1", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InlineResponse201 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "Lorum ipsum", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse201 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(example = "Lorum ipsum", description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public InlineResponse201 price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(example = "9.99", description = "")
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public InlineResponse201 isLocationOffer(Boolean isLocationOffer) {
    this.isLocationOffer = isLocationOffer;
    return this;
  }

   /**
   * Get isLocationOffer
   * @return isLocationOffer
  **/
  @Schema(example = "false", description = "")
  public Boolean isIsLocationOffer() {
    return isLocationOffer;
  }

  public void setIsLocationOffer(Boolean isLocationOffer) {
    this.isLocationOffer = isLocationOffer;
  }

  public InlineResponse201 isRental(Boolean isRental) {
    this.isRental = isRental;
    return this;
  }

   /**
   * Get isRental
   * @return isRental
  **/
  @Schema(example = "false", description = "")
  public Boolean isIsRental() {
    return isRental;
  }

  public void setIsRental(Boolean isRental) {
    this.isRental = isRental;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse201 inlineResponse201 = (InlineResponse201) o;
    return Objects.equals(this.id, inlineResponse201.id) &&
        Objects.equals(this.name, inlineResponse201.name) &&
        Objects.equals(this.description, inlineResponse201.description) &&
        Objects.equals(this.price, inlineResponse201.price) &&
        Objects.equals(this.isLocationOffer, inlineResponse201.isLocationOffer) &&
        Objects.equals(this.isRental, inlineResponse201.isRental);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, price, isLocationOffer, isRental);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse201 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    isLocationOffer: ").append(toIndentedString(isLocationOffer)).append("\n");
    sb.append("    isRental: ").append(toIndentedString(isRental)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
