/*
 * Toolshop API
 * Toolshop REST API technical description
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@testsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.practicesoftwaretesting.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InvoiceRequest
 */

@javax.annotation.Generated(value = "com.tesuqa.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-21T18:13:14.454153555Z[GMT]")

public class InvoiceRequest {
  @SerializedName("billing_address")
  private String billingAddress = null;

  @SerializedName("billing_city")
  private String billingCity = null;

  @SerializedName("billing_country")
  private String billingCountry = null;

  @SerializedName("billing_state")
  private String billingState = null;

  @SerializedName("billing_postcode")
  private String billingPostcode = null;

  @SerializedName("cart_id")
  private String cartId = null;

  public InvoiceRequest billingAddress(String billingAddress) {
    this.billingAddress = billingAddress;
    return this;
  }

   /**
   * Get billingAddress
   * @return billingAddress
  **/
  @Schema(description = "")
  public String getBillingAddress() {
    return billingAddress;
  }

  public void setBillingAddress(String billingAddress) {
    this.billingAddress = billingAddress;
  }

  public InvoiceRequest billingCity(String billingCity) {
    this.billingCity = billingCity;
    return this;
  }

   /**
   * Get billingCity
   * @return billingCity
  **/
  @Schema(description = "")
  public String getBillingCity() {
    return billingCity;
  }

  public void setBillingCity(String billingCity) {
    this.billingCity = billingCity;
  }

  public InvoiceRequest billingCountry(String billingCountry) {
    this.billingCountry = billingCountry;
    return this;
  }

   /**
   * Get billingCountry
   * @return billingCountry
  **/
  @Schema(description = "")
  public String getBillingCountry() {
    return billingCountry;
  }

  public void setBillingCountry(String billingCountry) {
    this.billingCountry = billingCountry;
  }

  public InvoiceRequest billingState(String billingState) {
    this.billingState = billingState;
    return this;
  }

   /**
   * Get billingState
   * @return billingState
  **/
  @Schema(description = "")
  public String getBillingState() {
    return billingState;
  }

  public void setBillingState(String billingState) {
    this.billingState = billingState;
  }

  public InvoiceRequest billingPostcode(String billingPostcode) {
    this.billingPostcode = billingPostcode;
    return this;
  }

   /**
   * Get billingPostcode
   * @return billingPostcode
  **/
  @Schema(description = "")
  public String getBillingPostcode() {
    return billingPostcode;
  }

  public void setBillingPostcode(String billingPostcode) {
    this.billingPostcode = billingPostcode;
  }

  public InvoiceRequest cartId(String cartId) {
    this.cartId = cartId;
    return this;
  }

   /**
   * Get cartId
   * @return cartId
  **/
  @Schema(example = "Cash on Delivery", description = "")
  public String getCartId() {
    return cartId;
  }

  public void setCartId(String cartId) {
    this.cartId = cartId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoiceRequest invoiceRequest = (InvoiceRequest) o;
    return Objects.equals(this.billingAddress, invoiceRequest.billingAddress) &&
        Objects.equals(this.billingCity, invoiceRequest.billingCity) &&
        Objects.equals(this.billingCountry, invoiceRequest.billingCountry) &&
        Objects.equals(this.billingState, invoiceRequest.billingState) &&
        Objects.equals(this.billingPostcode, invoiceRequest.billingPostcode) &&
        Objects.equals(this.cartId, invoiceRequest.cartId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billingAddress, billingCity, billingCountry, billingState, billingPostcode, cartId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoiceRequest {\n");
    
    sb.append("    billingAddress: ").append(toIndentedString(billingAddress)).append("\n");
    sb.append("    billingCity: ").append(toIndentedString(billingCity)).append("\n");
    sb.append("    billingCountry: ").append(toIndentedString(billingCountry)).append("\n");
    sb.append("    billingState: ").append(toIndentedString(billingState)).append("\n");
    sb.append("    billingPostcode: ").append(toIndentedString(billingPostcode)).append("\n");
    sb.append("    cartId: ").append(toIndentedString(cartId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
