/*
 * Toolshop API
 * Toolshop REST API technical description
 *
 * OpenAPI spec version: 5.0.0
 * Contact: info@testsmith.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.practicesoftwaretesting.client.model;

/**
* OneOfpaymentCheckBodyPaymentDetails
*/
public interface OneOfpaymentCheckBodyPaymentDetails {

}
